version: 2
updates:
  # Maintain dependencies for npm in frontend
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      frontend-deps:
        patterns:
          - "*"

  # Maintain dependencies for .NET in engine
  - package-ecosystem: "nuget"
    directory: "/engine/Poolr.Engine.Api"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      nuget-deps:
        patterns:
          - "*"

  # Maintain dependencies for Cargo in src-tauri
  - package-ecosystem: "cargo"
    directory: "/src-tauri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      cargo-deps:
        patterns:
          - "*"

  # Maintain GitHub Actions workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
