<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Version>0.6.3</Version>
    <AssemblyVersion>0.6.3.0</AssemblyVersion>
    <FileVersion>0.6.3.0</FileVersion>
    <Authors>M. Haris Awan</Authors>
    <Company>The Method Lab</Company>
    <Product>Poolr Statistics Engine</Product>
    <Description>High-performance statistics &amp; vector SVG rendering engine for Systematic Reviews and Meta-Analyses (PRISMA 2020)</Description>
    <PackageLicenseExpression>Proprietary</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/harisawan-bit/poolr</RepositoryUrl>
  </PropertyGroup>

</Project>
